on:
  push:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  run:
    name: Sync GitHub to Gitee
    runs-on: ubuntu-latest
    steps:
            
      - name: Mirror the GitHub repos to Gitee
        uses: Yikun/hub-mirror-action@v1.2
        with:
          src: github/simple-robot
          dst: gitee/simple-robot-project
          dst_key: ${{ secrets.SSH_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: simbot-component-mirai,simbot-component-tencent-guild,simbot-component-kaiheila,simbot-examples,simbot-mirai-login-helper
          account_type: org
          debug: true
          force_update: true
          
